### ISSUE TITLE
Crash after placing way too long piece of track (with golden spike)

### ISSUE THREAD

**Issue by themartin1** [TeamOpenIndustry/ImmersiveRailroading#671]
[crash-2019-11-09_20.15.22-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3827627/crash-2019-11-09_20.15.22-client.txt)

**Comment by cam72cam** [comment]
Please post the crash report

**Comment by cam72cam** [comment]
Or are you saying that you can create a piece of track that exceeds what's reasonable?

**Comment by themartin1** [comment]
Hey thank you for answering quickly! 
Can you see the crash report?? Sorry for not posting immidiately i accidently pressed enter key
the case are as following im gonna try to described it as best i can. And what i did to fix it.

I got a bit carried away and posted a long custom curve with the golden spike.
The tracked started to load in and removed blocks ( playing in creative). I flew from the starting point of the track and as i got further into the trackline and loading terrain about 75% of the track length) i got a crash i might be able to post the report aswell if u want.

i tried to reload but got a crash immidiately after laoding in. 

I then removed IMR from my custom modpack and was allowed to load in. 

I then got further down the track and saw the gravel rail bed had a cow stuck in it kinda buggy. I removed the cow and backtracked the track. I noticed a kinda of invisible outline of the track along where it had been placed. 

I now tried to load in IMR back into my custom modpack. I got some way down where the track had been but i got a crash again. 

**1st actual crash report**
[crash-2019-11-09_14.57.01-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3827633/crash-2019-11-09_14.57.01-client.txt)

**Comment by themartin1** [comment]
The cow was at the end of the track.

**Comment by cam72cam** [comment]
Ah, that's a snow crash, a known bug in the last version. https://github.com/TeamOpenIndustry/ImmersiveRailroading/issues/606#issuecomment-503757114 should fix it for you

**Comment by themartin1** [comment]
Ill give it a go. Thank you so much Cam7cam.

Also im so gratefull you spent time both on this site and developing! Im enjoying minecraft so much with IMR! 

Ill let you know if it fixes the problem.

**Comment by themartin1** [comment]
Im sorry the New version of IMR snowfix didnt seem to fix the problem. Can i send you the new crash report?

**Comment by themartin1** [comment]
**crash report after replacing Immersive railroading with actual twitch version **

[crash-2019-11-09_20.36.23-client.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3827652/crash-2019-11-09_20.36.23-client.txt)

**Comment by themartin1** [comment]
LMK if u can hep you in any way

**Comment by cam72cam** [comment]
I wonder if partially loading your world without IR has caused this problem.  You might not be able to have IR in this world now.

**Comment by themartin1** [comment]
I reckon. Its like half of the long piece of track is stuck in a limbo form since i saw the outline of the track when i was close to where it had been before i removed IR. 

But IR was supposed to be completly removed wiith the mod i clicked accept to that after removing the mod from the pack.

**Comment by cam72cam** [comment]
Try removing IR, then flying around all the places you have IR stuff in the world

**Comment by themartin1** [comment]
Played around abit and carried on with IE building. I have been flying around the area alot. 

Still when installed the snowfix version of IR that you had given me a link to yesterday in this thread i get a shut down immidiately 

[crash-2019-11-10_14.03.53-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3828453/crash-2019-11-10_14.03.53-server.txt)

**Comment by cam72cam** [comment]
Yeah, removing then re-adding IR corrupted it's ability to run in your world.

**Comment by themartin1** [comment]
Interessting. Are there any point in trying to fix an issue like that? I mean is it possible to fix.

**Comment by cam72cam** [comment]
You could try the test build I posted in #annoucements in discord.  That changed some of that stuff around under the hood.  Make sure you make a world backup first.

**Comment by themartin1** [comment]
**ImmersiveRailroading-1.6.1_1.12.2_guifix.jar**

Is that the one you mean i should try out ?

**Comment by cam72cam** [comment]
Yeah, that should work fine

**Comment by themartin1** [comment]
**[crash-2019-11-10_15.02.12-server.txt](https://github.com/TeamOpenIndustry/ImmersiveRailroading/files/3828522/crash-2019-11-10_15.02.12-server.txt)**

Unfortunately im still getting an immidiate shut down. Thank you very much Cam72cam

**Comment by cam72cam** [comment]
Sorry I could not help more

**Comment by cam72cam** [comment]
@themartin1 there's a setting in config/forge.cfg to remove erroring tile entities.  Try turning that on and loading your world.  Once you fly around a bit, it'll removed the bugged entities.
